### PR TITLE
Fix flaky tasks reverse test

### PR DESCRIPTION
**Pull request by Strift**
# Pull Request

Fixes a flaky tests about getting tasks in reverse order

### CODE REVIEW

**Comment by curquiza** [comment]
@Strift can you rebase the PR once `bump-meilisearch-v1.12` is merged? 😊

**Comment by Strift** [comment]
@curquiza managed to fix the flakiness of the test 🙌

**Review by curquiza — APPROVED** [review]
You're the best 🤘

bors merge

**Comment by curquiza** [comment]
a timeout, not the same flaky, hope it's really punctual 🤞

bors merge

**Pull request merged**
