### PR TITLE
Extract functionality to a more specific class

### PR DESCRIPTION
**Pull request by jonatanrdsantos**
# Pull Request
This PR is a copy of #270  to check the pipeline.

## What does this PR do?
 Applies clean code.
- Rename FailedJsonDecodingException to JsonDecodingException and FailedJsonEncodingException to JsonEncodingException, due to the Exception already making clear that it's a failure.
- Created a unique separated class to be used as JSON encode/decode across the system.
- Standardized the JSON Exception return messages.

## PR checklist
Please check if your PR fulfills the following requirements:
- [ ] Does this PR fix an existing issue?
- [X] Have you read the contributing guidelines?
- [X] Have you made sure that the title is accurate and descriptive of the changes?

Thank you so much for contributing to MeiliSearch!

### CODE REVIEW

**Comment by jonatanrdsantos** [comment]
@alallema Created this PR from a feature branch to see if it will break.

**Comment by jonatanrdsantos** [comment]
Hi @alallema, seems that the feature branch did not make the action work, so feel free to merge based on the comments on #270 .
I do not have a solution for that on my side. don't know why it's breaking.

**Review by alallema — APPROVED** [review]
Hi @jonatanrdsantos,
I don't know either why it broke the tests. But the PR on main seems to have solved the issue.
Thanks again for contributing to MeiliSearch ❤️

**Comment by alallema** [comment]
bors merge

**Pull request merged**
