### PR TITLE
Removed depreciated sys-info route closes

### LINKED ISSUE #65: Remove sys-info routes
As stated in https://github.com/meilisearch/MeiliSearch/pull/810 and https://github.com/meilisearch/integration-guides/issues/36 the sys-info routes will be considered as deprecated in MeiliSearch v0.13.0. These routes should be removed from this SDK accordingly.

### PR DESCRIPTION
**Pull request by ppshobi**

### CODE REVIEW

**Comment by Guikingone** [comment]
Hi 👋 

Is there any information about this deprecation on the official documentation? 🤔

**Comment by curquiza** [comment]
@Guikingone this is a future change you can see in the MeiliSearch repository:
- in the Milestones: https://github.com/meilisearch/MeiliSearch/milestone/8
- in this issue: https://github.com/meilisearch/MeiliSearch/issues/824

So, the official documentation is not deployed yet for the v0.13.0 since the v0.13.0 is not out. Maybe what you suggest right now is to warn about this deprecation in the current documentation to inform the user? Like a "will be deprecated" flag?
If this is what you mean, you can open an issue in the [dedicated documentation repository](https://github.com/meilisearch/documentation/) 🙂

**Comment by curquiza** [comment]
@ppshobi can you point this PR to the branch `meilisearch-bump-v0.13.0` (https://github.com/meilisearch/meilisearch-php/pull/68) instead of master since the v0.13.0 is not out 🙂

**Comment by Guikingone** [comment]
@curquiza Yes, I think it could be a good idea to inform about this deprecation with a version note, maybe something like this:

```
Deprecated: Since v0.13.0
```

**Comment by curquiza** [comment]
@Guikingone! You're right! An issue in the dedicated repo would be perfect 🙂🚀

**Comment by ppshobi** [comment]
Base branch changed, Sorry didn't notice that the base branch was not out yet

**Comment by curquiza** [comment]
@ppshobi! It was not created, I've just created it for your PR 😉

**Comment by curquiza** [comment]
@ppshobi could you rebase your branch according to `meilisearch-bump-v0.13.0` (not `master`) please? 🙂

**Comment by ppshobi** [comment]
Thank you

**Pull request merged**
