### PR TITLE
Remove unneeded deps

### LINKED ISSUE #652: php-http/httplug and php-http/client-common are not required deps anymore?
**Description**
I don't see any usage of these packages

**Basic example**
- I see only php-http/discovery is the package that is used

**Other**
Remove them ?

### PR DESCRIPTION
**Pull request by norkunas**
# Pull Request

## Related issue
Fixes #652

## What does this PR do?
- Removes unneeded `php-http/httplug` and `php-http/client-common` dependencies. This PR is based on #651 to see if it really doesn't break anything. So #651 should be merged before this and after that I'll rebase this PR.

## PR checklist
Please check if your PR fulfills the following requirements:
- [x] Does this PR fix an existing issue, or have you listed the changes applied in the PR description (and why they are needed)?
- [x] Have you read the contributing guidelines?
- [x] Have you made sure that the title is accurate and descriptive of the changes?

### CODE REVIEW

**Review by brunoocasali — DISMISSED** [review]

**Comment by norkunas** [comment]
```
1) Tests\Settings\EmbeddersTest::testUpdateEmbeddersWithHuggingFace
Meilisearch\Exceptions\TimeOutException: Request timed out

/home/runner/work/meilisearch-php/meilisearch-php/src/Endpoints/Tasks.php:56
/home/runner/work/meilisearch-php/meilisearch-php/src/Endpoints/Delegates/HandlesTasks.php:47
/home/runner/work/meilisearch-php/meilisearch-php/tests/Settings/EmbeddersTest.php:81
phpvfscomposer:///home/runner/work/meilisearch-php/meilisearch-php/vendor/phpunit/phpunit/phpunit:106
```

this test looks flaky to me, as it randomly fails

**Comment by norkunas** [comment]
and now I see again codecov/project job has failed

**Comment by curquiza** [comment]
@norkunas if I'm correct this CI will not prevent from merging
Maybe we could set up a minimal coverage, like 75% of coverage, here we have already 83%?

What do you think @brunoocasali

**Comment by norkunas** [comment]
ping @brunoocasali

**Review by brunoocasali — APPROVED** [review]
I will approve again and force merge. It seems codecov is comparing this branch with the latest coverage seen in main. So, I guess if we just rebase this branch it should be fine.

**Comment by brunoocasali** [comment]
bors merge

**Pull request merged**
