### PR TITLE
Drop PHP 7.3 support

### LINKED ISSUE #179: Discussion the drop support of PHP v7.3
Hi,

I began using MeiliSearch recently, and with PHP for a personal project

Regarding:

- https://www.php.net/supported-versions.php
- https://packagist.org/packages/meilisearch/meilisearch-php/php-stats#0.18

I am opening this issue to discuss the minimum version of this package, I think requiring PHP v7.4 could improve the codebase for the better, and will be very happy to contribute to :)

Feel free to close, related to https://github.com/meilisearch/meilisearch-php/issues/136 and https://github.com/meilisearch/meilisearch-php/issues/165

Cheers!

### PR DESCRIPTION
**Pull request by mmachatschek**
# Pull Request

## What does this PR do?
Fixes #179

This sets the minimum PHP-version to 7.4 which still receives security fixes. PHP 7.3 has [reached its EOL](https://www.php.net/supported-versions.php) in december.

## PR checklist
Please check if your PR fulfills the following requirements:
- [x] Does this PR fix an existing issue?
- [x] Have you read the contributing guidelines?
- [x] Have you made sure that the title is accurate and descriptive of the changes?

### CODE REVIEW

**Comment by alallema** [comment]
Hi @mmachatschek,
Thank you for all your PR ❤️ ! I'm a bit late on PR on this repo but I will try to review everything tomorrow.
I see that there are some additional fixes on this PR. Would it be possible to cut this into two PR for clarity ?
Thanks again 😊

**Comment by mmachatschek** [comment]
@alallema I moved the additional updates to a seperate PR

**Review by alallema — APPROVED** [review]
Thanks, @mmachatschek 🎉 
LGTM!

**Comment by alallema** [comment]
bors try

**Comment by alallema** [comment]
bors try

**Comment by alallema** [comment]
bors merge

**Comment by alallema** [comment]
Oupsy seems I made a mistake in the order bors 😄

**Pull request merged**
