### PR TITLE
Add distinct attribute at search

### LINKED ISSUE #646: [v1.9] Distinct field at search time
Related to https://github.com/meilisearch/integration-guides/issues/301

### Explanation of the feature

Introduction of a new search parameter `distinct` to apply distinct attribute at search time. The attributes must be filterable (added to `filterableAttributes`) to be used in `distinct`

Usage: https://meilisearch.notion.site/Set-distinctAttribute-at-search-usage-947187b312c04616a8ca8ef5bcc5c63c

### TODO

- [ ] Add a new search parameter named `distinct` 
- [ ] Add tests.

⚠️ Make PRs pointing to `bump-meilisearch-v1.9.0` and NOT `main`. Please do 1 PR for all of these changes, and not several.

### PR DESCRIPTION
**Pull request by ManyTheFish**
# Pull Request

Forked from #648 

## Related issue
Fixes #646

## What does this PR do?
- Add distinct attribute at search

## PR checklist
Please check if your PR fulfills the following requirements:
- [x] Does this PR fix an existing issue, or have you listed the changes applied in the PR description (and why they are needed)?
- [x] Have you read the contributing guidelines?
- [x] Have you made sure that the title is accurate and descriptive of the changes?

Thank you so much for contributing to Meilisearch!

### CODE REVIEW

**Comment by curquiza** [comment]
If you have time @norkunas, since we don't move on https://github.com/meilisearch/meilisearch-php/pull/648 (the contributor already made a lot, I can understand they don't have the time now, but release is next Monday)

**Comment by norkunas** [comment]
@curquiza if you think that tests are fine, then I'm ok with merging it

**Review by norkunas — APPROVED** [review]

**Comment by curquiza** [comment]
Many will fix the tests and we are good, thank you for your reactivity ❤️

**Comment by ManyTheFish** [comment]
closing this PR in favor of https://github.com/meilisearch/meilisearch-php/pull/648

**Pull request closed without merging**
