### PR TITLE
added type to http client property

### PR DESCRIPTION
**Pull request by b3none**
# Pull Request

## Related issue
Not related to an issue - should add contin

## What does this PR do?
It adds the type to the private class property `$http`.

## PR checklist
Please check if your PR fulfills the following requirements:
- [ ] Does this PR fix an existing issue, or have you listed the changes applied in the PR description (and why they are needed)?
- [ ] Have you read the contributing guidelines?
- [ ] Have you made sure that the title is accurate and descriptive of the changes?

Thank you so much for contributing to Meilisearch!

### CODE REVIEW

**Comment by curquiza** [comment]
Hello @b3none 

Thanks for your PR 😊 
Since there is no issue, could you explain a little bit more about this change?
What is the purpose of it, I mean the value of changing this? If yes, is there any other part in the code base that would need this kind of change as well?

**Comment by b3none** [comment]
> Hello @b3none
> 
> Thanks for your PR 😊 Since there is no issue, could you explain a little bit more about this change? What is the purpose of it, I mean the value of changing this? If yes, is there any other part in the code base that would need this kind of change as well?

@curquiza from what I’ve seen this is used everywhere, I think this one was missed because of the name class so I’ve switched to an alias.

The change makes the code more declarative, improve the speed and reliability of typehint generation as well as not allow anyone to set the $http class property to anything other than what it’s expecting.

**Comment by curquiza** [comment]
Ok thank you!
However, all the tests are failing, can you fix it so that I can merge the PR?

**Comment by b3none** [comment]
@curquiza try that

**Comment by b3none** [comment]
Yeah I give up with this, i've already got my 4 hacktoberfest PRs 😂

**Pull request closed without merging**
