### PR TITLE
Make createdAt and updatedAt DateTime types not string

### PR DESCRIPTION
**Pull request by brunoocasali**
- Replace the `string` type by `?DateTime` in `Endpoints\Indexes::createdAt` and `Endpoints\Indexes::updatedAt`

### CODE REVIEW

**Comment by norkunas** [comment]
Why not start to use `DateTimeImmutable`? :) One day DateTime could be deprecated https://www.reddit.com/r/PHP/comments/w7v4pb/deprecating_the_mutable_datetime_class/

**Comment by brunoocasali** [comment]
> Why not start to use `DateTimeImmutable`? :) One day DateTime could be deprecated

Hi @norkunas, I appreciate the idea and agree with it, but I think it is too soon to make a change like that. Let's wait for more info on the PHP core team.

**Comment by norkunas** [comment]
> > Why not start to use `DateTimeImmutable`? :) One day DateTime could be deprecated
> 
> Hi @norkunas, I appreciate the idea and agree with it, but I think it is too soon to make a change like that. Let's wait for more info on the PHP core team.

Okay but why is your preference is to use `DateTime` which has no upsides over `DateTimeImmutable`?

**Review by alallema — APPROVED** [review]
LGTM! 🌯

**Comment by brunoocasali** [comment]
bors merge

**Comment by brunoocasali** [comment]
bors cancel

**Pull request merged**
