### PR TITLE
Make use of environment variable in PHPUnit

### PR DESCRIPTION
**Pull request by mmachatschek**
# Pull Request

## What does this PR do?
DX enhancement

This will make it possible to override the default HOST and APIKEY parameter without modifying the base `TestCase` class. If you run multiple instances of meilisearch locally you just need to copy the `phpunit.xml.dist` to `phpunit.xml` and override the appropriate value. `phpunit.xml` is ignored by git. PHPunit will use `phpunit.xml.dist` only if `phpunit.xml` doesn't exist.

## PR checklist
Please check if your PR fulfills the following requirements:
- [ ] Does this PR fix an existing issue?
- [x] Have you read the contributing guidelines?
- [x] Have you made sure that the title is accurate and descriptive of the changes?

### CODE REVIEW

**Review by mmachatschek — COMMENTED** [review]
If PR #282 gets merged. The .gitattributes value needs to be updated as well

**Comment by alallema** [comment]
bors try

**Comment by mmachatschek** [comment]
@alallema There is one change missing to thie .gitattributes file. Im pushing it in a minute

**Comment by alallema** [comment]
> @alallema There is one change missing in the .gitattributes file. Im pushing it in a minute
Yes, I just saw it! Thanks.
Anyway, I had bors trouble.

**Review by alallema — APPROVED** [review]
Thanks for this PR @mmachatschek !
I really like your additions 😊

**Comment by alallema** [comment]
bors merge

**Comment by alallema** [comment]
bors merge

**Pull request merged**
