### PR TITLE
Add CI to update library version

### PR DESCRIPTION
**Pull request by curquiza**
I cannot test it directly before merging it sorry -> this is how `workflow_dispatch` works with GitHub Actions

@mmachatschek and @norkunas I pinged both of you to be aware of the tool, but I only need one review 😊

### CODE REVIEW

**Comment by norkunas** [comment]
Maybe we could integrate https://github.com/Roave/BackwardCompatibilityCheck

**Comment by curquiza** [comment]
@norkunas good idea!
I would rather we do this in another PR however 😊

**Review by norkunas — APPROVED** [review]

**Review by mmachatschek — APPROVED** [review]
I don't have a strong opinion on which Github Action tool to use. but the changes LGTM

**Comment by curquiza** [comment]
bors merge

**Pull request merged**
