### PR TITLE
Update the version for the next release (v1.0.0)

### PR DESCRIPTION
**Pull request by brunoocasali**
This version makes this package compatible with Meilisearch v1.0.0 :tada:
Check out the changelog of [Meilisearch v1.0.0](https://github.com/meilisearch/meilisearch/releases/tag/v1.0.0) for more information on the changes.

### 💥 Breaking Changes

- `Endpoints/Indexes` date attributes `$createdAt` and `$updatedAt` are `DateTime` now instead of `string`.
  - Removed `getCreatedAtString` and `getUpdatedAtString` functions.
- Add `canceledBy`/`setCanceledBy` in `TasksQuery`
- Remove `next` attribute and `setNext` from `TasksQuery`.
- Remove `next` attribute and `setNext` from `DeleteTasksQuery`.
- Remove `next`, `canceledBy` attributes and `setNext`, `setCanceledBy` from `CancelTasksQuery`.
- Remove `deleteAllIndexes`, since they don't really delete all the indexes but only the first page.
- Remove `getAllRawIndexes` function.
- Rename `getAllIndexes` to `getIndexes`.
- Move all traits to `src/Endpoints/Delegates`.
  - `Meilisearch\Delegates\HandlesIndex` to `Meilisearch\Endpoints\Delegates\HandlesIndex`
  - `Meilisearch\Delegates\HandlesSystem` to `Meilisearch\Endpoints\Delegates\HandlesSystem`
  - `Meilisearch\Delegates\TasksQueryTrait` to `Meilisearch\Endpoints\Delegates\TasksQueryTrait`

### CODE REVIEW

**Comment by bidoubiwa** [comment]
> Remove next attribute and setNext from TasksQuery.

Is it from `tasksQuery` or `CancelTasksQuery` ?

**Review by bidoubiwa — APPROVED** [review]
LGTM 🔥

**Review by alallema — APPROVED** [review]
LGTM! 🎉 
There is more than just this PR in the Changelog maybe one missed the `skip-changelog` label

**Comment by brunoocasali** [comment]
bors merge

**Pull request merged**
