### PR TITLE
Added CodeCov coverage report support

### LINKED ISSUE #567: Add CodeCov
⚠️ This issue is generated, it means the examples and the namings do not necessarily correspond to the language of this repository.
Also, if you are a maintainer, please add any clarification and instructions about this issue.

Sorry if this is already wholly/partially implemented. Feel free to let me know about the state of this issue in the repo.

Related to https://github.com/meilisearch/integration-guides/issues/59

----

Codecov helps us to know if a PR add non-tested code. If it's the case, we don't accept the PR. 
It's easy to install, easy to configure.

### TODO:

- [ ] Add CodeCov to this repository.
- [ ] Add the CodeCov badge on this repository README.md
- [ ] Ensure a minimum coverage is accepted (optional)

### PR DESCRIPTION
**Pull request by connorhu**
# Pull Request

## Related issue
Fixes #567

## What does this PR do?
- Integrates CodeCov as I did at https://github.com/meilisearch/meilisearch-symfony/pull/322

## PR checklist
Please check if your PR fulfills the following requirements:
- [x] Does this PR fix an existing issue, or have you listed the changes applied in the PR description (and why they are needed)?
- [x] Have you read the contributing guidelines?
- [x] Have you made sure that the title is accurate and descriptive of the changes?

Thank you so much for contributing to Meilisearch!

### CODE REVIEW

**Comment by curquiza** [comment]
@norkunas if you have the time and you are around, feel free to review this one as well (same work than on the Symfony repo)

**Comment by connorhu** [comment]
To be honest, I don't know why the test stopped.

**Comment by curquiza** [comment]
@connorhu 
re-running

**Comment by connorhu** [comment]
Rebased the PR to keep the main behind it up-to-date.

**Review by norkunas — APPROVED** [review]

**Comment by norkunas** [comment]
bors merge

**Pull request merged**
