### PR TITLE
Improvements to the test suites

### PR DESCRIPTION
**Pull request by ppshobi**
In this PR I have tried to clean up the test suite a little. Since this is my first contribution towards the repo I have constrained myself from making any big change. I have basically autoloaded some of the files to avoid manual file inclusions via statements like `require_once` since `composer` does that automatically for us. Also added a `phpunit.xml` to make test running easier. 

Hopefully, once you merge this I can come up with some good improvements.

### CODE REVIEW

**Comment by curquiza** [comment]
Hello @ppshobi! Thanks for your really useful contribution!!! 🎉

I see there is a lot of conflicts, it's my fault, I've just merged another PR with a lot of changes in tests before seeing yours.
But of course I would rather we apply your changes in tests part! 🙂

So, could you rebase and I will review it?
Thanks again!

**Comment by ppshobi** [comment]
Sure. I will rebase it. and update the PR

**Comment by ppshobi** [comment]
Rebased onto master. If you would like me to squash commits I could do that, but I made each commits as small changes, so you could review it easily. Let me know what you think.

**Comment by curquiza** [comment]
Thanks! It's really weird: I can see the changes of my previous PR on yours... It should not.

**Comment by curquiza** [comment]
Thanks a lot, again, for your useful contribution! Merging! 😄

**Comment by ppshobi** [comment]
Thank you :)

**Pull request merged**
