### PR TITLE
Use json throw on error flag

### PR DESCRIPTION
**Pull request by norkunas**

### CODE REVIEW

**Comment by codedge** [comment]
LGTM! 👍

**Comment by norkunas** [comment]
Not sure how to resolve so many failing tests :see_no_evil:

**Comment by alallema** [comment]
> Not sure how to resolve so many failing tests 🙈

I neither the code looks fine 😄 . I will check on my side too.
Also, you can launch the test locally with:
` sh scripts/tests.sh`

**Comment by norkunas** [comment]
Okay so based on docs for example after deleting index it returns 204 status code and so we should not try to parse the response at all

**Comment by norkunas** [comment]
Please approve CI run :)

**Review by alallema — APPROVED** [review]
Thanks a lot for this PR @norkunas!

**Comment by alallema** [comment]
bors merge

**Comment by norkunas** [comment]
Thanks for merge :)

**Pull request merged**
