### PR TITLE
Changes related to the next Meilisearch release (v1.4.0)

### PR DESCRIPTION
**Pull request by alallema**
related to: https://github.com/meilisearch/integration-guides/issues/286

### CODE REVIEW

**Review by curquiza — CHANGES_REQUESTED** [review]
@alallema 
Can you change the routes named `wordDictionary` into `dictionary` only: there is no `word` in the route anymore 

Sorry for the confusion

**Comment by alallema** [comment]
Yes of course!
Doesn't take into account my review of the code-sample ... sorry

**Comment by curquiza** [comment]
> And the route name is correct, did you mean the method?
Yes, my bad for confusion, the method name!

**Review by curquiza — APPROVED** [review]
Thank you @alallema 😊

**Comment by curquiza** [comment]
Converting this to draft to avoid anyone from merging before 25/09

**Comment by curquiza** [comment]
bors merge

**Pull request merged**
