### PR TITLE
Improve coding standards

### PR DESCRIPTION
**Pull request by norkunas**
# Pull Request

## Related issue
Fixes #<issue_number>

## What does this PR do?
- Add missing phpdocs;
- Replace `DateTime` with `DateTimeinterface` to encourage usage of `DateTimeImmutable`;
- Add more tests for contracts;
- Make tests a little bit more consistent;
- Add missing php typehints;

## PR checklist
Please check if your PR fulfills the following requirements:
- [ ] Does this PR fix an existing issue, or have you listed the changes applied in the PR description (and why they are needed)?
- [x] Have you read the contributing guidelines?
- [x] Have you made sure that the title is accurate and descriptive of the changes?

### CODE REVIEW

**Comment by norkunas** [comment]
I cannot understand if delete tasks query test was properly defined or not because https://www.meilisearch.com/docs/reference/api/tasks#delete-tasks does not indicate the `cancelledBy` query param type :expressionless:

**Comment by curquiza** [comment]
I don't understand norkunas, why would you pass `null` as an array?

Also, maybe the docs contains mistakes, but canceledBy is here: https://www.meilisearch.com/docs/reference/api/tasks#canceledby

**Comment by norkunas** [comment]
> I don't understand @norkunas, why would you pass `null` as an array?

Not null as array, but null as item in array, see the previous code: `(new DeleteTasksQuery())->setCanceledBy([null])`

> What's the purpose of this PR?

To make codebase consistent?

> Also, maybe the docs contains mistakes, but canceledBy is here: https://www.meilisearch.com/docs/reference/api/tasks#canceledby

Ok so it accepts an integer and if multiple then it needs to be joined by comma. I've made the contract to explicitly say `non-empty-array<int>`

**Comment by curquiza** [comment]
> Not null as array, but null as item in array, see the previous code: (new DeleteTasksQuery())->setCanceledBy([null])

Yes sorry, I got it but not said it correctly. But why do you need to pass null? This is not the purpose of canceling a task. the purpose is to pass the uid of the task(s) to cancel them

**Comment by norkunas** [comment]
> > Not null as array, but null as item in array, see the previous code: (new DeleteTasksQuery())->setCanceledBy([null])
> 
> Yes sorry, I got it but not said it correctly. But why do you need to pass null? This is not the purpose of canceling a task. the purpose is to pass the uid of the task(s) to cancel them

I don't. That was the existing test which is nonsense

**Comment by curquiza** [comment]
> I don't. That was the existing test which is nonsense

Indeed, sounds weird to me, we can change it/remove it.

**Comment by curquiza** [comment]
@norkunas can you improve
- the title of the PR
- describes in some points (not a lot of details) what you are achieving in this PR?

There are a lot of changes

**Comment by norkunas** [comment]
> @norkunas can you improve
> 
> * the title of the PR
> * describes in some points (not a lot of details) what you are achieving in this PR?
> 
> There are a lot of changes

Done

**Review by curquiza — APPROVED** [review]
bors merge

**Pull request merged**
