### PR TITLE
Maintenance CI and code base

### LINKED ISSUE #619: Split CI tests with different http clients into separate jobs
**Description**
Currently tests job takes much time because it dynamically updates dependencies and re-run tests with different http client.
Better would be to split into separate jobs so they could run faster and also fail faster (and cancel workflow).
Also we'd see in the checks list with which http clients we test without opening the jobs.

**Basic example**
-
**Other**
-

### PR DESCRIPTION
**Pull request by norkunas**
# Pull Request

## Related issue
Fixes #619

## What does this PR do?
- Enables parallel config in cs fixer;
- Uses cs fixer shim to avoid conflicts between dependencies;
- Splits CI tests jobs with matrix to run in parallel for faster feedback;
- Uses `ramsey/composer-install` in CI to allow caching dependencies;

## PR checklist
Please check if your PR fulfills the following requirements:
- [ ] Does this PR fix an existing issue, or have you listed the changes applied in the PR description (and why they are needed)?
- [x] Have you read the contributing guidelines?
- [x] Have you made sure that the title is accurate and descriptive of the changes?

### CODE REVIEW

**Comment by norkunas** [comment]
@curquiza CI job names has changed and in repository settings some of them are marked as required but not exists anymore

**Comment by curquiza** [comment]
Thank you I review it next week 👍

**Comment by norkunas** [comment]
@curquiza I think we need a codecov token to fix `codecov/project` CI job

**Review by curquiza — APPROVED** [review]
Niiiice thanks @norkunas 

bors merge

**Comment by curquiza** [comment]
OMG, still having this bors message...

Capture d’écran 2024-07-03 à 14 13 23

**Comment by curquiza** [comment]
@norkunas I think to avoid this issue you can open PR directly on the origin repo, you have the access 😊 But bors should work anyway, I agree.....

**Comment by norkunas** [comment]
> @norkunas, next time I think to avoid this issue you can open PR directly on the origin repo, you have the access 😊 But bors should work anyway, I agree.....

I always work in a fork to avoid messing up branches in upstream :)

**Comment by brunoocasali** [comment]
bors cancel

**Comment by brunoocasali** [comment]
bors merge

**Comment by brunoocasali** [comment]
I don't think we have any issue with codecoverage, bors is the one causing troubles here! I'm going to merge manually since everything worked!

**Pull request merged**
