### PR TITLE
Fix logging for ApiException

### PR DESCRIPTION
**Pull request by curquiza**
oops 😇

### CODE REVIEW

**Review by bidoubiwa — DISMISSED** [review]
bors merge

**Comment by bidoubiwa** [comment]
bors -r

**Comment by curquiza** [comment]
My bad! I fixed the tests 😇

**Comment by bidoubiwa** [comment]
Sorry if i'm mistaken, but since the error name is different is this not a breaking change for users that tries to catch that specific error?

**Comment by curquiza** [comment]
It's only the displayed logs when the error is raised, the name (in the code) is still the same -> `MeiliSearchApiException`, so the code of the users will not be breaking.
From my POV changing this kind of logs, I mean used during development, is not breaking for the usage. But if you would rather consider this kind of change as breaking, be free to use the `breaking change` label 🙂

**Review by bidoubiwa — APPROVED** [review]
I see! It's oke for me.

**Comment by bidoubiwa** [comment]
bors merge

**Pull request merged**
