### PR TITLE
Add more details MeiliSearch\Exceptions\ApiException

### PR DESCRIPTION
**Pull request by claudiunicolaa**
Discussed here https://github.com/meilisearch/meilisearch-php/issues/50

### CODE REVIEW

**Review by curquiza — DISMISSED** [review]
🚀 
Waiting for the @bidoubiwa review before the merge 😇

**Comment by bidoubiwa** [comment]
Hey @claudiunicolaa. Thanks a lot for your contribution. I tried looking how we could test that these parameters are well retrievable from the thrown exceptions but apparently it is not possible in [PHPunit](https://phpunit.readthedocs.io/en/9.5/writing-tests-for-phpunit.html?highlight=expectException#testing-exceptions) or at least I did not found out how.

Do you know a way? If no, no problem the PR looks good to me!

**Comment by claudiunicolaa** [comment]
hey @bidoubiwa. I guess will work instead of expecting a exception - for example
```php
$this->expectException(ApiException::class);
$this->client->updateIndex('indexB', ['primaryKey' => 'objectID']);
```
to catch the exception and assert the public properties, the __toString() output, or both combined.
```php
        // assert independent
        try {
            $this->client->updateIndex('indexB', ['primaryKey' => 'objectID']);
        } catch (ApiException $apiException) {
            $this->assertEquals(400, $apiException->httpStatus);
            $this->assertEquals("A primary key is already present. It's impossible to update it", $apiException->message);
            $this->assertEquals("primary_key_already_present", $apiException->errorCode);
            $this->assertEquals("invalid_request_error", $apiException->errorType);
            $this->assertEquals("https://docs.meilisearch.com/errors#primary_key_already_present", $apiException->errorLink);
        }
```

```php
        // assert __toString()
        try {
            $this->client->updateIndex('indexB', ['primaryKey' => 'objectID']);
        } catch (ApiException $apiException) {
            $expectedExceptionToString = "MeiliSearch HTTPRequestException: Http Status: 400 - Message: A primary key is already present. It's impossible to update it - Error code: primary_key_already_present - Error type: invalid_request_error - Error link: https://docs.meilisearch.com/errors#primary_key_already_present";
            $this->assertEquals($expectedExceptionToString, (string)$apiException);
        }
```
It would be enough but will introduce a lot of hardcoded text in many test classes.

Creating a test class for ApiException sounds better to me
```php
final class ApiExceptionTest extends TestCase
{
    public function testException(): void
    {
        $httpBodyExample = [
            'message' => 'A primary key is already present. It\'s impossible to update it',
            'errorCode' => 'primary_key_already_present',
            'errorType' => 'invalid_request_error',
            'errorLink' => 'https://docs.meilisearch.com/errors#primary_key_already_present',
        ];
        $statusCode = 400;

        try {
            throw new ApiException($statusCode, $httpBodyExample);
        } catch (ApiException $apiException) {
            $this->assertEquals($statusCode, $apiException->httpStatus);
            $this->assertEquals($httpBodyExample['message'],
                $apiException->message);
            $this->assertEquals($httpBodyExample['errorCode'], $apiException->errorCode);
            $this->assertEquals($httpBodyExample['errorType'], $apiException->errorType);
            $this->assertEquals($httpBodyExample['errorLink'], $apiException->errorLink);

            $expectedExceptionToString = "MeiliSearch HTTPRequestException: Http Status: {$statusCode} - Message: {$httpBodyExample['message']} - Error code: {$httpBodyExample['errorCode']} - Error type: {$httpBodyExample['errorType']} - Error link: {$httpBodyExample['errorLink']}";
            $this->assertEquals($expectedExceptionToString, (string) $apiException);
        }
    }
}
```

**Comment by bidoubiwa** [comment]
Thanks a lot for the investigation! 

As error text and links may change between MeiliSearch version without introducing a braking change we should not test their value. But the 'erroCode' should not change unless breaking update in MeiliSearch. So I think we should only test the value of errorCode and just check if the other parameters exist on your error (or maybe just the type?)

**Comment by bidoubiwa** [comment]
I removed what is not trustable data and we are left with this: 

```php
final class ApiExceptionTest extends TestCase
{
    public function testException(): void
    {
        $errorCode = 'primary_key_already_present';
        $statusCode = 400;

        try {
            throw new ApiException($statusCode, $httpBodyExample);
        } catch (ApiException $apiException) {
            
            $this->assertEquals($errorCode, $apiException->errorCode);
            $this->assertEquals($statusCode, $apiException->httpStatus);
            $this->assertIsString($apiException->message);
            $this->assertIsString($apiException->errorType);
            $this->assertIsString($apiException->errorLink);
        }
    }
}

```

**Comment by claudiunicolaa** [comment]
Check out the [commit](https://github.com/meilisearch/meilisearch-php/pull/150/commits/ff829bca25ddd7130b1d0097a376837af2766b44). 
Being a unit test, we don't really care about the string values but will help us to test if `__toString()` makes what is supposed to make

**Review by bidoubiwa — APPROVED** [review]
Ah yes! Way better approach :) LGTM 🔥

**Comment by bidoubiwa** [comment]
bors merge

**Pull request merged**
