### PR TITLE
Force empty object when encoding json

### LINKED ISSUE #209: Implementation of a Json Serializer
**Description**
As a result of this [issue](https://github.com/meilisearch/meilisearch-php/issues/204), it appears that `json_decode` transforms
```json
"synonyms": {}
```
into
```php
["synonyms"]=>
  array(0) {
}
```
In the same way as:
```json
"stopWords": []
```
become:
```php
["stopWords"]=>
  array(0) {
}
```
The problem appears when you send back the synonyms array to the MeiliSearch API who only take:
```json
"synonyms": {},
```
or
```json
"synonyms": null,
```
It could be useful to implement our own specific JsonSerializer to check if every data send back to MeiliSearch API are well-formatted.

In the meanwhile a patch will be created [see](https://github.com/meilisearch/meilisearch-php/pull/208).

### PR DESCRIPTION
**Pull request by norkunas**
# Pull Request

## What does this PR do?
Fixes #209

## PR checklist
Please check if your PR fulfills the following requirements:
- [x] Does this PR fix an existing issue?
- [x] Have you read the contributing guidelines?
- [x] Have you made sure that the title is accurate and descriptive of the changes?

### CODE REVIEW

**Comment by alallema** [comment]
Hi @norkunas,
Thanks a lot for this PR! We currently are in releasing process of the new version of MeiliSearch v0.25.0 and the release of v0.21.0 of this package. So I will merge your PR right after.

**Comment by norkunas** [comment]
I saw it, no problem :)

**Comment by norkunas** [comment]
Will check tomorrow why tests are red

**Comment by norkunas** [comment]
Ok so in fact there it forces array to objects in too many places and we have no control over it. So imho there is nothing todo and the code already is good as it is or we should add some tool as a dependency which allows to construct body for json based on schemas (if meilisearch exposes openapi or something) and serialize by it.

**Comment by alallema** [comment]
Thanks a lot @norkunas !

**Pull request closed without merging**
